environment: "none"


exporter:
  name: "metoro-exporter"
  replicas: 2
  otlpUrl: "http://change_me:4317"
  clickhouseUrl: "change_me:9000"
  clickhouseDatabase: "change_me"
  clickhouseUser: "change_me"
  prometheusUrl: "http://change_me:9090"
  image:
    repository: index.docker.io/metoro/metoro-exporter
    pullPolicy: "Always"
  # Placeholder configmap
  configMap:
    name: "exporter-config"
    values:
      config.yml: |-
        Some Config Key

exporterSecret:
  name: "exporter-secret"
  bearerToken: "CHANGE_ME"