apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.exporterSecret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AUTH_TOKEN: {{ .Values.exporterSecret.bearerToken | b64enc | quote }}
  CLICKHOUSE_PASSWORD: {{ .Values.exporterSecret.clickhousePassword | b64enc | quote }}
